<?php

namespace AppBundle\Repository;

/**
 * inventtransRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inventtransRepository extends \Doctrine\ORM\EntityRepository
{
}
