<?php

namespace AppBundle\Repository;

/**
 * InventDimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventDimRepository extends \Doctrine\ORM\EntityRepository
{
}
