<?php

namespace AppBundle\Repository;

/**
 * onhandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class onhandRepository extends \Doctrine\ORM\EntityRepository
{
}
