<?php

namespace AppBundle\Repository;

/**
 * processRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class processRepository extends \Doctrine\ORM\EntityRepository
{
}
