<?php

namespace AppBundle\Repository;

/**
 * tasksusersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tasksusersRepository extends \Doctrine\ORM\EntityRepository
{
}
