<?php

namespace AppBundle\Repository;

/**
 * wherehouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wherehouseRepository extends \Doctrine\ORM\EntityRepository
{
}
