<?php

namespace AppBundle\Repository;

/**
 * yacheikaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class yacheikaRepository extends \Doctrine\ORM\EntityRepository
{
}
